version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: innovsurf_mysql_db
    environment:
      MYSQL_DATABASE: innovsurf
      MYSQL_ROOT_PASSWORD: '' # Utiliser cette variable pour autoriser un mot de passe root vide
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # Autorisation d'utiliser un mot de passe vide pour root
    ports:
      - "3307:3306" # Changer le port exposé à 3307 pour éviter les conflits
    volumes:
      - mysql_data:/var/lib/mysql # Ajout du volume pour la persistance des données
    networks:
      - innovsurf_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: innovsurf_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '' # Utilisation du mot de passe root vide
    depends_on:
      - db
    ports:
      - "8080:80" # Exposition de PhpMyAdmin sur le port 8080
    networks:
      - innovsurf_net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80 || exit 1"]
      interval: 10s
      retries: 3
      timeout: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: innovsurf_backend
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=innovsurf
      - DB_USER=root
      - DB_PASSWORD=
    ports:
      - "8000:8000" # Exposition de Django sur le port 8000
    depends_on:
      db:
        condition: service_healthy
      phpmyadmin:
        condition: service_healthy
    networks:
      - innovsurf_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: innovsurf_frontend
    ports:
      - "3000:3000" # Exposition de React sur le port 3000
    networks:
      - innovsurf_net

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: innovsurf_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    networks:
      - innovsurf_net

networks:
  innovsurf_net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
