# Generated by Django 5.1 on 2024-09-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
